"use strict";

const MessageTypes = {
  CLEAR_COMPLETED_COMMAND: "CLEAR_COMPLETED_COMMAND",
  DESTROY_COMMAND: "DESTROY_COMMAND",
  EDIT_COMMAND: "EDIT_COMMAND",
  NEW_TODO_COMMAND: "NEW_TODO_COMMAND",
  TOGGLE_ALL_COMMAND: "TOGGLE_ALL_COMMAND",
  TOGGLE_COMMAND: "TOGGLE_COMMAND",

  ALL_TODOS_QUERY: "ALL_TODOS_QUERY",
  ACTIVE_TODOS_QUERY: "ACTIVE_TODOS_QUERY",
  COMPLETED_TODOS_QUERY: "COMPLETED_TODOS_QUERY",
};

export default MessageTypes;
