"use strict";

const MessageTypes = {
  CLEAR_COMPLETED_COMMAND: "CLEAR_COMPLETED_COMMAND",
  DESTROY_COMMAND: "DESTROY_COMMAND",
  EDIT_COMMAND: "EDIT_COMMAND",
  NEW_TODO_COMMAND: "NEW_TODO_COMMAND",
  TOGGLE_ALL_COMMAND: "TOGGLE_ALL_COMMAND",
  TOGGLE_COMMAND: "TOGGLE_COMMAND",

  TODO_LIST_QUERY: "TODO_LIST_QUERY",
};

export default MessageTypes;
